---

- hosts: Web-host
  become: true
  tasks:

  - name: install apache package
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: restart httpd
    systemd:
      name: httpd
      state: restarted
