---

- hosts: all
  become: yes
  tasks:
  - name: install updates Rocky 
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install updates Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: Web-host
  become: yes 
  tasks:
  - name: install Apache httpd
    dnf:
      name:
        - httpd
        - php
      state: latest

  - name: copy default html for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

