---
- name: Install Apache
  hosts: Web_host
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: latest


- name: Start httpd
  hosts: Web_host
  tasks:
    - name: Start Apache
      service:
        name: httpd
        state: started

